Switching ruby version
2019/01/04 19:56:53 error running command "gem install bundler": exit status 1, skipper: defaulting to running command ["/bin/bash" "-c" "gem install bundler < /dev/null"] because the base dependency graph is missing
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3`
	bundler requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.